import fs from 'node:fs'

const dataPath = new URL('../frontend/public/seichi_data.json', import.meta.url)
const existing = JSON.parse(fs.readFileSync(dataPath, 'utf8'))
const deprecatedIds = new Set([
  'megami-poem-miura-01',
  'kugenuma-bunnygirl-01',
  'aobuta-fujisawa-station-01',
  'aobuta-katase-enoshima-01',
  'aobuta-enoshima-koya-01',
  'miura-megami-poem-01',
  'megami-miura-market-01',
])

const common = {
  verified: true,
  source: '',
  generic_intro_en: '',
}

const aobutaTitleJa = '青春ブタ野郎はバニーガール先輩の夢を見ない'
const aobutaTitleEn = 'Rascal Does Not Dream of Bunny Girl Senpai'

function makeAobutaQuest({
  id,
  spot_name_ja,
  spot_name_en,
  scene_description,
  intro_short_en,
  lat,
  lng,
  area,
  nearest_station,
  access_note,
  photo_url,
  tags,
  hours,
  quest_title,
  quest_place,
  quest_type,
  category,
  title,
  description,
  photo_prompt,
  impression_prompt,
}) {
  return {
    id,
    spot_name_ja,
    spot_name_en,
    anime_title_ja: aobutaTitleJa,
    anime_title_en: aobutaTitleEn,
    scene_description,
    intro_short_en,
    lat,
    lng,
    area,
    nearest_station,
    access_note,
    photo_url,
    tags,
    official_url: 'https://aobuta.com/',
    hours,
    quest_title,
    quest_place,
    quest_type,
    quests: [
      {
        category,
        title,
        description,
        photo_prompt,
        impression_prompt,
      },
    ],
  }
}

const aobutaSpots = [
  makeAobutaQuest({
    id: 'aobuta-01-fujisawa-station',
    spot_name_ja: '藤沢駅',
    spot_name_en: 'Fujisawa Station',
    scene_description: '青ブタ巡礼の出発地点として使いやすい藤沢駅。湘南エリアへ向かう前の起点として写真に残す。',
    intro_short_en: 'Fujisawa Station is the starting gate for this Bunny Girl Senpai route. It anchors the trip before the route heads toward Enoshima and the coast.',
    lat: 35.3389,
    lng: 139.4875,
    area: 'Fujisawa, Kanagawa',
    nearest_station: 'JR / Odakyu / Enoden Fujisawa Station',
    access_note: '藤沢駅からスタート',
    photo_url: '/quest-assets/aobuta-01-fujisawa-station.jpg',
    tags: ['walkable', 'station', 'photo-spot', 'free', 'outdoor'],
    hours: 'Always open',
    quest_title: '藤沢駅スタートクエスト',
    quest_place: '藤沢駅',
    quest_type: 'Photo',
    category: 'Photo',
    title: '藤沢駅を撮る',
    description: '青ブタ巡礼の出発地点として、藤沢駅の駅舎や駅前を写真に残す。',
    photo_prompt: 'Upload a photo that clearly shows Fujisawa Station.',
    impression_prompt: 'What did this starting point feel like?',
  }),
  makeAobutaQuest({
    id: 'aobuta-02-dennys-fujisawa-exterior',
    spot_name_ja: 'デニーズ藤沢北口店',
    spot_name_en: "Denny's Fujisawa North Exit",
    scene_description: '藤沢駅北口側にある食事スポット。作中の印象的なファミレス場面を思い出せる場所として扱う。',
    intro_short_en: "Denny's Fujisawa North Exit adds an everyday food stop to the Bunny Girl Senpai route. The exterior photo keeps the quest quick while still tying the memory to Fujisawa.",
    lat: 35.3424,
    lng: 139.4877,
    area: 'Fujisawa, Kanagawa',
    nearest_station: 'Fujisawa Station',
    access_note: '藤沢駅北口から徒歩圏内',
    photo_url: '/quest-assets/aobuta-02-dennys-fujisawa-exterior.jpg',
    tags: ['restaurant', 'photo-spot', 'walkable', 'outdoor'],
    hours: 'Restaurant hours vary',
    quest_title: 'デニーズ藤沢北口店クエスト',
    quest_place: 'デニーズ藤沢北口店',
    quest_type: 'Photo',
    category: 'Photo',
    title: 'デニーズ藤沢北口店を撮る',
    description: '店の外観や看板など、デニーズ藤沢北口店だと分かる写真を撮る。',
    photo_prompt: "Upload a photo that clearly shows Denny's Fujisawa North Exit.",
    impression_prompt: 'What detail made this feel like the scene?',
  }),
  makeAobutaQuest({
    id: 'aobuta-03-dennys-fujisawa-omelette',
    spot_name_ja: 'デニーズ藤沢北口店のオムライス',
    spot_name_en: "Denny's Fujisawa Omelette Rice",
    scene_description: 'デニーズ藤沢北口店でオムライスを食べるフードクエスト。食べたオムライスの写真をアルバムに入れる。',
    intro_short_en: 'This food quest is about eating omelette rice at Denny’s Fujisawa. The album photo should show the omelette rice from the visit.',
    lat: 35.3424,
    lng: 139.4877,
    area: 'Fujisawa, Kanagawa',
    nearest_station: 'Fujisawa Station',
    access_note: 'デニーズ藤沢北口店で注文',
    photo_url: '/quest-assets/aobuta-03-dennys-fujisawa-omelette.jpg',
    tags: ['food', 'restaurant', 'story-food', 'paid', 'indoor'],
    hours: 'Restaurant hours vary',
    quest_title: 'デニーズでオムライスを食べるクエスト',
    quest_place: 'デニーズ藤沢北口店',
    quest_type: 'Food Photo',
    category: 'Food Photo',
    title: 'デニーズのオムライスを食べる',
    description: 'デニーズ藤沢北口店でオムライスを食べて、そのオムライスの写真を残す。',
    photo_prompt: 'Upload a photo of the omelette rice you ate at Denny’s Fujisawa.',
    impression_prompt: 'What did you order?',
  }),
  makeAobutaQuest({
    id: 'aobuta-04-katase-enoshima-station',
    spot_name_ja: '片瀬江ノ島駅',
    spot_name_en: 'Katase-Enoshima Station',
    scene_description: '江ノ島方面の印象的な駅舎。湘南らしい景色へ入る入口として写真に残す。',
    intro_short_en: 'Katase-Enoshima Station is a strong visual gateway into the coastal side of the Bunny Girl Senpai pilgrimage. Its distinctive building makes the route instantly recognizable.',
    lat: 35.3089,
    lng: 139.4824,
    area: 'Katase, Fujisawa',
    nearest_station: 'Katase-Enoshima Station',
    access_note: '小田急 片瀬江ノ島駅すぐ',
    photo_url: '/quest-assets/aobuta-04-katase-enoshima-station.jpg',
    tags: ['walkable', 'station', 'photo-spot', 'free', 'outdoor'],
    hours: 'Always open',
    quest_title: '片瀬江ノ島駅クエスト',
    quest_place: '片瀬江ノ島駅',
    quest_type: 'Photo',
    category: 'Photo',
    title: '片瀬江ノ島駅を撮る',
    description: '江ノ島エリア巡礼の入口として駅舎を記録する。',
    photo_prompt: 'Upload a photo that clearly shows Katase-Enoshima Station.',
    impression_prompt: 'What makes this feel like Enoshima?',
  }),
  makeAobutaQuest({
    id: 'aobuta-05-benten-bridge',
    spot_name_ja: '弁天橋',
    spot_name_en: 'Benten Bridge',
    scene_description: '江ノ島へ向かう橋の景色。夜景や橋上の雰囲気を写真に残す。',
    intro_short_en: 'Benten Bridge connects the station area with Enoshima itself. A photo here captures the route turning from town into island scenery.',
    lat: 35.3046,
    lng: 139.4828,
    area: 'Katase / Enoshima, Fujisawa',
    nearest_station: 'Katase-Enoshima Station',
    access_note: '片瀬江ノ島駅から江ノ島方面へ徒歩',
    photo_url: '/quest-assets/aobuta-05-benten-bridge.jpg',
    tags: ['walkable', 'bridge', 'photo-spot', 'free', 'outdoor', 'night-view'],
    hours: 'Always open',
    quest_title: '弁天橋フォトクエスト',
    quest_place: '弁天橋',
    quest_type: 'Photo',
    category: 'Photo',
    title: '弁天橋を撮る',
    description: '橋や江ノ島方面の景色など、弁天橋だと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Benten Bridge or the Enoshima approach.',
    impression_prompt: 'What was the light or weather like?',
  }),
  makeAobutaQuest({
    id: 'aobuta-06-enoshima-aquarium',
    spot_name_ja: '新江ノ島水族館',
    spot_name_en: 'Enoshima Aquarium',
    scene_description: '片瀬海岸沿いの水族館。入口や外観を撮って、湘南の定番スポットとして記録する。',
    intro_short_en: 'Enoshima Aquarium is an easy coastal landmark on the Bunny Girl Senpai route. Its entrance photo makes a clear album stop near Katase-Enoshima.',
    lat: 35.3101,
    lng: 139.4795,
    area: 'Katasekaigan, Fujisawa',
    nearest_station: 'Katase-Enoshima Station',
    access_note: '片瀬江ノ島駅から徒歩約3分',
    photo_url: '/quest-assets/aobuta-06-enoshima-aquarium.jpg',
    tags: ['aquarium', 'photo-spot', 'walkable', 'paid', 'outdoor'],
    hours: 'Aquarium hours vary',
    quest_title: '新江ノ島水族館クエスト',
    quest_place: '新江ノ島水族館',
    quest_type: 'Photo',
    category: 'Photo',
    title: '新江ノ島水族館を撮る',
    description: '水族館の入口や外観など、新江ノ島水族館だと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Enoshima Aquarium.',
    impression_prompt: 'What stood out at the aquarium entrance?',
  }),
  makeAobutaQuest({
    id: 'aobuta-07-enoshima-koya-exterior',
    spot_name_ja: '江ノ島小屋',
    spot_name_en: 'Enoshima Koya',
    scene_description: '江ノ島周辺の食体験スポット。店の外観を撮って、湘南グルメの立ち寄り先として記録する。',
    intro_short_en: 'Enoshima Koya turns the pilgrimage into a food-side stop near the water. The exterior photo keeps the route grounded in a real Shonan visit.',
    lat: 35.3065,
    lng: 139.4816,
    area: 'Katase, Fujisawa',
    nearest_station: 'Katase-Enoshima Station',
    access_note: '片瀬江ノ島駅から徒歩圏内',
    photo_url: '/quest-assets/aobuta-07-enoshima-koya-exterior.jpg',
    tags: ['restaurant', 'photo-spot', 'walkable', 'outdoor'],
    hours: 'Restaurant hours vary',
    quest_title: '江ノ島小屋クエスト',
    quest_place: '江ノ島小屋',
    quest_type: 'Photo',
    category: 'Photo',
    title: '江ノ島小屋を撮る',
    description: '店の外観や入口など、江ノ島小屋だと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Enoshima Koya.',
    impression_prompt: 'How did this food stop fit into the route?',
  }),
  makeAobutaQuest({
    id: 'aobuta-08-enoshima-koya-shirasu-don',
    spot_name_ja: '江ノ島小屋のしらす丼',
    spot_name_en: 'Enoshima Koya Shirasu Bowl',
    scene_description: '江ノ島小屋でしらす丼を食べるフードクエスト。食べたしらす丼の写真をアルバムに入れる。',
    intro_short_en: 'This food quest is about eating a shirasu bowl at Enoshima Koya. The album photo should show the shirasu bowl from the visit.',
    lat: 35.3065,
    lng: 139.4816,
    area: 'Katase, Fujisawa',
    nearest_station: 'Katase-Enoshima Station',
    access_note: '江ノ島小屋で注文',
    photo_url: '/quest-assets/aobuta-08-enoshima-koya-shirasu-don.jpg',
    tags: ['food', 'story-food', 'walkable', 'paid', 'indoor'],
    hours: 'Restaurant hours vary',
    quest_title: '江ノ島しらす丼クエスト',
    quest_place: '江ノ島小屋',
    quest_type: 'Food Photo',
    category: 'Food Photo',
    title: '江ノ島小屋のしらす丼を食べる',
    description: '江ノ島小屋でしらす丼を食べて、そのしらす丼の写真を残す。',
    photo_prompt: 'Upload a photo of the shirasu bowl you ate at Enoshima Koya.',
    impression_prompt: 'What did this meal taste like?',
  }),
  makeAobutaQuest({
    id: 'aobuta-09-kamakura-kokomae-crossing',
    spot_name_ja: '鎌倉高校前踏切',
    spot_name_en: 'Kamakurakokomae Crossing',
    scene_description: '江ノ電と海を同時に感じられる踏切。安全に配慮しながら、場所が分かる写真を撮る。',
    intro_short_en: 'Kamakurakokomae Crossing is one of the clearest coastal rail views on the route. The quest asks for a recognizable, safely taken photo rather than a perfect recreation.',
    lat: 35.3069,
    lng: 139.5009,
    area: 'Kamakura, Kanagawa',
    nearest_station: 'Kamakurakokomae Station',
    access_note: '江ノ電 鎌倉高校前駅から徒歩すぐ。踏切周辺では安全に注意',
    photo_url: '/quest-assets/aobuta-09-kamakura-kokomae-crossing.jpg',
    tags: ['railway', 'photo-spot', 'walkable', 'free', 'outdoor', 'caution-crowds'],
    hours: 'Always open',
    quest_title: '鎌倉高校前踏切クエスト',
    quest_place: '鎌倉高校前踏切',
    quest_type: 'Photo',
    category: 'Photo',
    title: '鎌倉高校前踏切を撮る',
    description: '踏切や江ノ電、海沿いの景色など、鎌倉高校前踏切だと分かる写真を撮る。',
    photo_prompt: 'Upload a safe photo that clearly shows Kamakurakokomae Crossing.',
    impression_prompt: 'What made this crossing memorable?',
  }),
  makeAobutaQuest({
    id: 'aobuta-10-shichirigahama-beach',
    spot_name_ja: '七里ヶ浜海岸',
    spot_name_en: 'Shichirigahama Beach',
    scene_description: '江ノ島を望める海岸。湘南らしい海と空の写真を巡礼アルバムに残す。',
    intro_short_en: 'Shichirigahama Beach gives the route a wide coastal pause. A photo here captures the Enoshima view and the open Shonan mood.',
    lat: 35.3065,
    lng: 139.5101,
    area: 'Kamakura, Kanagawa',
    nearest_station: 'Shichirigahama Station',
    access_note: '江ノ電 七里ヶ浜駅から徒歩圏内',
    photo_url: '/quest-assets/aobuta-10-shichirigahama-beach.jpg',
    tags: ['beach', 'photo-spot', 'walkable', 'free', 'outdoor'],
    hours: 'Always open',
    quest_title: '七里ヶ浜海岸クエスト',
    quest_place: '七里ヶ浜海岸',
    quest_type: 'Photo',
    category: 'Photo',
    title: '七里ヶ浜海岸を撮る',
    description: '海岸や江ノ島方面の眺めなど、七里ヶ浜らしい写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Shichirigahama Beach or the Enoshima view.',
    impression_prompt: 'What did the coast feel like?',
  }),
  makeAobutaQuest({
    id: 'aobuta-11-toshimaya-hato-sable',
    spot_name_ja: '豊島屋本店',
    spot_name_en: 'Toshimaya Honten',
    scene_description: '鳩サブレーを購入するお土産クエスト。豊島屋本店で箱や購入したものを写真に残す。',
    intro_short_en: 'Toshimaya Honten adds a Kamakura souvenir stop to the Bunny Girl Senpai route. Photographing Hato Sable makes the album feel like a completed day trip.',
    lat: 35.3206,
    lng: 139.5537,
    area: 'Kamakura, Kanagawa',
    nearest_station: 'Kamakura Station',
    access_note: 'JR鎌倉駅東口から徒歩圏内',
    photo_url: '/quest-assets/aobuta-11-toshimaya-hato-sable.jpg',
    tags: ['souvenir', 'shop', 'walkable', 'paid', 'indoor'],
    hours: 'Store hours vary',
    quest_title: '鳩サブレークエスト',
    quest_place: '豊島屋本店',
    quest_type: 'Souvenir Photo',
    category: 'Souvenir Photo',
    title: '豊島屋本店で鳩サブレーを撮る',
    description: '豊島屋本店で購入した鳩サブレーの箱や袋などを写真に残す。',
    photo_prompt: 'Upload a photo of Hato Sable or your souvenir from Toshimaya Honten.',
    impression_prompt: 'Who would you share this souvenir with?',
  }),
  makeAobutaQuest({
    id: 'aobuta-12-hakkeijima-station',
    spot_name_ja: '八景島駅',
    spot_name_en: 'Hakkeijima Station',
    scene_description: '海の生き物が描かれた駅構内が印象的なスポット。八景島到着の写真として記録する。',
    intro_short_en: 'Hakkeijima Station marks the start of the route’s Yokohama side. Its sea-life stair artwork makes it a distinct photo quest.',
    lat: 35.3403,
    lng: 139.6419,
    area: 'Kanazawa, Yokohama',
    nearest_station: 'Hakkeijima Station',
    access_note: 'シーサイドライン 八景島駅',
    photo_url: '/quest-assets/aobuta-12-hakkeijima-station.jpg',
    tags: ['station', 'photo-spot', 'walkable', 'free', 'indoor'],
    hours: 'Station hours',
    quest_title: '八景島駅クエスト',
    quest_place: '八景島駅',
    quest_type: 'Photo',
    category: 'Photo',
    title: '八景島駅を撮る',
    description: '駅構内や階段の装飾など、八景島駅だと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Hakkeijima Station.',
    impression_prompt: 'What detail stood out inside the station?',
  }),
  makeAobutaQuest({
    id: 'aobuta-13-hakkeijima-sea-paradise',
    spot_name_ja: '横浜・八景島シーパラダイス',
    spot_name_en: 'Yokohama Hakkeijima Sea Paradise',
    scene_description: '八景島側の目的地。入口や看板、施設外観など、シーパラダイスだと分かる写真を撮る。',
    intro_short_en: 'Yokohama Hakkeijima Sea Paradise is the route’s big destination on the Yokohama side. A recognizable entrance or sign photo makes a clear final quest.',
    lat: 35.336056,
    lng: 139.644583,
    area: 'Kanazawa, Yokohama',
    nearest_station: 'Hakkeijima Station',
    access_note: 'シーサイドライン 八景島駅から徒歩圏内',
    photo_url: '/quest-assets/aobuta-13-hakkeijima-sea-paradise.jpg',
    tags: ['aquarium', 'theme-park', 'photo-spot', 'walkable', 'paid', 'outdoor'],
    hours: 'Facility hours vary',
    quest_title: '八景島シーパラダイスクエスト',
    quest_place: '横浜・八景島シーパラダイス',
    quest_type: 'Photo',
    category: 'Photo',
    title: '八景島シーパラダイスを撮る',
    description: '入口や看板、施設外観など、八景島シーパラダイスだと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Yokohama Hakkeijima Sea Paradise.',
    impression_prompt: 'How did this final stop feel?',
  }),
]

const megamiTitleJa = '女神のカフェテラス'
const megamiTitleEn = 'The Cafe Terrace and Its Goddesses'

function makeMegamiQuest({
  id,
  spot_name_ja,
  spot_name_en,
  scene_description,
  intro_short_en,
  lat,
  lng,
  area,
  nearest_station,
  access_note,
  photo_url,
  tags,
  hours,
  quest_title,
  quest_place,
  quest_type,
  category,
  title,
  description,
  photo_prompt,
  impression_prompt,
}) {
  return {
    id,
    spot_name_ja,
    spot_name_en,
    anime_title_ja: megamiTitleJa,
    anime_title_en: megamiTitleEn,
    scene_description,
    intro_short_en,
    lat,
    lng,
    area,
    nearest_station,
    access_note,
    photo_url,
    tags,
    official_url: 'https://goddess-cafe.com/',
    hours,
    quest_title,
    quest_place,
    quest_type,
    quests: [
      {
        category,
        title,
        description,
        photo_prompt,
        impression_prompt,
      },
    ],
  }
}

const megamiSpots = [
  makeMegamiQuest({
    id: 'megami-01-coffee-house-poem',
    spot_name_ja: 'コーヒーハウスぽえむ 三浦海岸駅前店',
    spot_name_en: 'Coffee House Poem Miura Kaigan',
    scene_description: '作中の喫茶店Familiaのモデルとして知られるカフェ。三浦海岸駅前の入口や外観を写真に残す。',
    intro_short_en: 'Coffee House Poem near Miura Kaigan Station is the core cafe stop for The Cafe Terrace and Its Goddesses. A recognizable exterior photo makes the route easy to explain.',
    lat: 35.1886,
    lng: 139.6535,
    area: 'Miura Coast, Kanagawa',
    nearest_station: 'Miura Kaigan Station',
    access_note: '京急 三浦海岸駅から徒歩すぐ',
    photo_url: '/quest-assets/megami-01-coffee-house-poem.jpg',
    tags: ['cafe', 'photo-spot', 'walkable', 'food', 'indoor'],
    hours: 'Cafe hours vary',
    quest_title: 'コーヒーハウスぽえむクエスト',
    quest_place: 'コーヒーハウスぽえむ 三浦海岸駅前店',
    quest_type: 'Photo',
    category: 'Photo',
    title: 'コーヒーハウスぽえむを撮る',
    description: '店の入口や外観など、コーヒーハウスぽえむだと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Coffee House Poem Miura Kaigan.',
    impression_prompt: 'What detail felt most like Familia?',
  }),
  makeMegamiQuest({
    id: 'megami-02-yokohama-baysis',
    spot_name_ja: '横浜BAYSIS',
    spot_name_en: 'Yokohama BAYSIS',
    scene_description: '関内エリアのライブハウス。入口や看板など、横浜BAYSISだと分かる写真を撮る。',
    intro_short_en: 'Yokohama BAYSIS adds a live-house stop to the Goddess Cafe Terrace route. The entrance photo connects the city-night side of the story to a real Kannai venue.',
    lat: 35.4461,
    lng: 139.6359,
    area: 'Kannai, Yokohama',
    nearest_station: 'Kannai Station',
    access_note: 'JR関内駅から徒歩圏内',
    photo_url: '/quest-assets/megami-02-yokohama-baysis.jpg',
    tags: ['live-house', 'photo-spot', 'walkable', 'night-view', 'indoor'],
    hours: 'Venue hours vary',
    quest_title: '横浜BAYSISクエスト',
    quest_place: '横浜BAYSIS',
    quest_type: 'Photo',
    category: 'Photo',
    title: '横浜BAYSISを撮る',
    description: '入口や看板など、横浜BAYSISだと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Yokohama BAYSIS.',
    impression_prompt: 'What was the city-night mood like?',
  }),
  makeMegamiQuest({
    id: 'megami-03-kannai-north-crossing',
    spot_name_ja: '関内駅北口交差点',
    spot_name_en: 'Kannai Station North Exit Crossing',
    scene_description: '関内駅北口近くの交差点。駅前の横断歩道や高架周辺など、場所が分かる写真を残す。',
    intro_short_en: 'Kannai Station North Exit Crossing is a quick city-scene quest near the station. It gives the route a recognizable Yokohama street memory.',
    lat: 35.445087,
    lng: 139.63518,
    area: 'Kannai, Yokohama',
    nearest_station: 'Kannai Station',
    access_note: 'JR関内駅北口から徒歩すぐ',
    photo_url: '/quest-assets/megami-03-kannai-north-crossing.jpg',
    tags: ['street', 'crossing', 'photo-spot', 'walkable', 'free', 'outdoor'],
    hours: 'Always open',
    quest_title: '関内駅北口交差点クエスト',
    quest_place: '関内駅北口交差点',
    quest_type: 'Photo',
    category: 'Photo',
    title: '関内駅北口交差点を撮る',
    description: '横断歩道や駅前の景色など、関内駅北口交差点だと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Kannai Station North Exit Crossing.',
    impression_prompt: 'What made this street scene stand out?',
  }),
  makeMegamiQuest({
    id: 'megami-04-miura-vegetable-market',
    spot_name_ja: '三浦やさい直売所',
    spot_name_en: 'Miura Vegetable Market',
    scene_description: '三浦らしい生活感を足せるローカルスポット。野菜売り場や直売所の雰囲気を写真に残す。',
    intro_short_en: 'The Miura vegetable market adds local life to the cafe route. A market photo makes the album feel connected to the neighborhood, not only the cafe.',
    lat: 35.1882,
    lng: 139.6542,
    area: 'Miura Coast, Kanagawa',
    nearest_station: 'Miura Kaigan Station',
    access_note: '京急 三浦海岸駅から徒歩約1分',
    photo_url: '/quest-assets/megami-04-miura-vegetable-market.jpg',
    tags: ['market', 'souvenir', 'walkable', 'food', 'outdoor'],
    hours: 'Store hours vary',
    quest_title: '三浦やさい直売所クエスト',
    quest_place: '三浦やさい直売所',
    quest_type: 'Photo',
    category: 'Photo',
    title: '三浦やさい直売所を撮る',
    description: '野菜売り場や直売所の看板など、三浦やさい直売所だと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows the Miura vegetable market.',
    impression_prompt: 'What local item caught your eye?',
  }),
  makeMegamiQuest({
    id: 'megami-05-miura-beach',
    spot_name_ja: '三浦海岸',
    spot_name_en: 'Miura Beach',
    scene_description: '三浦海岸の海辺。砂浜や海岸線など、三浦海岸だと分かる写真を撮る。',
    intro_short_en: 'Miura Beach gives the Goddess Cafe Terrace route its open seaside mood. A beach photo works well as a quiet album memory.',
    lat: 35.1848,
    lng: 139.6545,
    area: 'Miura Coast, Kanagawa',
    nearest_station: 'Miura Kaigan Station',
    access_note: '京急 三浦海岸駅から徒歩圏内',
    photo_url: '/quest-assets/megami-05-miura-beach.jpg',
    tags: ['beach', 'photo-spot', 'walkable', 'free', 'outdoor', 'night-view'],
    hours: 'Always open',
    quest_title: '三浦海岸クエスト',
    quest_place: '三浦海岸',
    quest_type: 'Photo',
    category: 'Photo',
    title: '三浦海岸を撮る',
    description: '砂浜や海岸線など、三浦海岸らしい写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Miura Beach.',
    impression_prompt: 'What did the seaside feel like?',
  }),
  makeMegamiQuest({
    id: 'megami-06-jogashima-park',
    spot_name_ja: '城ヶ島公園',
    spot_name_en: 'Jogashima Park',
    scene_description: '城ヶ島の自然公園。灯台や広場、海を望む景色など、城ヶ島公園だと分かる写真を残す。',
    intro_short_en: 'Jogashima Park extends the route to the southern edge of Miura. Its open lawns, lighthouse, and ocean views make a strong final photo quest.',
    lat: 35.130537,
    lng: 139.626525,
    area: 'Jogashima, Miura',
    nearest_station: 'Misakiguchi Station',
    access_note: '京急 三崎口駅から城ヶ島行きバスを利用',
    photo_url: '/quest-assets/megami-06-jogashima-park.jpg',
    tags: ['park', 'photo-spot', 'scenic', 'free', 'outdoor'],
    hours: 'Park hours vary',
    quest_title: '城ヶ島公園クエスト',
    quest_place: '城ヶ島公園',
    quest_type: 'Photo',
    category: 'Photo',
    title: '城ヶ島公園を撮る',
    description: '灯台や広場、海を望む景色など、城ヶ島公園だと分かる写真を撮る。',
    photo_prompt: 'Upload a photo that clearly shows Jogashima Park.',
    impression_prompt: 'How did this final Miura stop feel?',
  }),
]

const assignedSpots = [
  ...aobutaSpots,
  ...megamiSpots,
  {
    id: 'hakone-initiald-01',
    spot_name_ja: '箱根旧道七曲り',
    spot_name_en: 'Hakone Old Road Nanamagari',
    anime_title_ja: '頭文字D Fifth Stage',
    anime_title_en: 'Initial D: Fifth Stage',
    scene_description: '箱根のヘアピンが続く山道。ドライブ体験は安全運転スコアとして扱う。',
    intro_short_en: 'Hakone Old Road Nanamagari is the clearest touge quest for the Initial D side of the app. The goal is not speed: the app frames it as a safe-drive route with checkpoints, smoothness, and respect.',
    lat: 35.2091,
    lng: 139.0587,
    area: 'Hakone, Kanagawa',
    nearest_station: 'Hakone-Yumoto Station',
    access_note: '箱根湯本駅からバスまたは車でアクセス。公道のため安全第一',
    photo_url: '/quest-assets/initiald-nanamagari.jpg',
    tags: ['driving-route', 'scenic', 'free', 'caution-active-road', 'outdoor'],
    official_url: '',
    hours: 'Always open',
    quest_title: 'Touge Safe Drive Quest',
    quest_place: '箱根旧道 七曲り',
    quest_type: 'Drive Mode',
    quests: [
      {
        category: 'Drive',
        title: 'Drive Modeを開く',
        description: '速度ではなく、スムーズさとチェックポイント通過でスコア化する。',
        photo_prompt: 'Upload a safe roadside or route-start photo. Do not upload while driving.',
        impression_prompt: 'Which sector did you try?',
      },
      {
        category: 'Safety',
        title: '安全に停車できる場所で記録する',
        description: '公道なので走行中の撮影は禁止。停車できる場所で記録する。',
        photo_prompt: 'Upload a photo taken only after safely stopping.',
        impression_prompt: 'What safety rule did you follow?',
      },
    ],
  },
]

const byId = new Map(existing.filter(spot => !deprecatedIds.has(spot.id)).map(spot => [spot.id, spot]))
for (const spot of assignedSpots) {
  byId.set(spot.id, { ...common, ...byId.get(spot.id), ...spot })
}

const next = [...byId.values()]
fs.writeFileSync(dataPath, `${JSON.stringify(next, null, 2)}\n`)
